version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: enemdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+mysqlconnector://user:pass@db:3306/enemdb
    ports:
      - "5000:5000"
volumes:
  db_data:
